services :
  installer :
    container_name: azuracast_installer
    image: pratik9722/azuracast_playlist:delivery
    volumes:
      - './:/installer'
    restart: 'no'
    entrypoint: ''
    command: docker_installer
